### ISSUE TITLE
sign in error

### ISSUE THREAD

**Issue by Fakemayham084** [sharkiqlibs/sharkiq#53]
PS C:\Users\mayha\Desktop\Chrismas Thing> & C:/Users/mayha/AppData/Local/Microsoft/WindowsApps/python3.11.exe "c:/Users/mayha/Desktop/Chrismas Thing/main.py"
Traceback (most recent call last):
  File "c:\Users\mayha\Desktop\Chrismas Thing\main.py", line 7, in <module>
    ayla_api.sign_in()
  File "C:\Users\mayha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sharkiq\ayla_api.py", line 93, in sign_in
    self._set_credentials(resp.status_code, resp.json())
  File "C:\Users\mayha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sharkiq\ayla_api.py", line 82, in _set_credentials
    raise SharkIqAuthError(login_result["error"]["message"])
                           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'

**Comment by JeffResc** [comment]
Closing as duplicate of #51.
